const profile = [
    {
        id: 'TNTruong',
        username: 'truong',
        password: '123',
        name: 'Trịnh Nam Trường',
        img: '/img/avatar.jpg',
        position: 'Thực tập',
        email: 'fireclub95@gmail.com',
        address: 'Ninh Bình',
        phoneNumber: '0866914221',
        birthday: '06/03/2000',
    },
    {
        id: 'TQKhanh',
        username: 'khanh',
        password: '123',
        name: 'Trịnh Quốc Khánh',
        img: '/img/icon-login.png',
        position: 'Thực tập',
        email: 'khanh@gmail.com',
        address: 'Ninh Bình',
        phoneNumber: '0866914221',
        birthday: '02/09/2010',
    },
    {
        id: 'TBNgoc',
        username: 'ngoc',
        password: '123',
        name: 'Trịnh Bảo Ngọc',
        img: '/img/icon-login.png',
        position: 'Thực tập',
        email: 'ngoc@gmail.com',
        address: 'Ninh Bình',
        phoneNumber: '0866914221',
        birthday: '21/11/2005',
    },
    {
        id: 'VADinh',
        username: 'dinh',
        password: '123',
        name: 'Vừ A Dính',
        img: '/img/icon-login.png',
        position: 'Thực tập',
        email: 'dinh@gmail.com',
        address: 'Ninh Bình',
        phoneNumber: '0866914221',
        birthday: '01/01/1999',
    },
    {
        id: 'TBNgoc',
        username: 'ngoc',
        password: '123',
        name: 'Trịnh Bảo Ngọc',
        img: '/img/icon-login.png',
        position: 'Thực tập',
        email: 'ngoc@gmail.com',
        address: 'Ninh Bình',
        phoneNumber: '0866914221',
        birthday: '21/11/2005',
    },
    {
        id: 'VADinh',
        username: 'dinh',
        password: '123',
        name: 'Vừ A Dính',
        img: '/img/icon-login.png',
        position: 'Thực tập',
        email: 'dinh@gmail.com',
        address: 'Ninh Bình',
        phoneNumber: '0866914221',
        birthday: '01/01/1999',
    }
]
export default profile;